from typing import NamedTuple


class TableIdentity(NamedTuple):
    schema: str
    table_name: str
    col_name: str


common_ml_tables = [
    TableIdentity("ML", "RECO_USER_PROGS_ADULTSWIM_LATEST_v2", "user_id"),
    TableIdentity("ML", "RECO_USER_PROGS_OCS_LATEST_v2", "user_id"),
    TableIdentity("ML", "RECO_USER_PROGS_CINEPLUS_LATEST_v2", "user_id"),
    TableIdentity("ML", "RECO_USER_TVBUNDLES_LATEST", "user_id"),
    TableIdentity("ML", "RECO_USER_PROGS_THIS_DAY_LATEST", "user_id"),
    TableIdentity("ML", "RECO_USER_CATEGORYS_LATEST", "user_id"),
    TableIdentity("ML", "RECO_USER_PROGS_THIS_WEEK_LATEST", "user_id"),
    TableIdentity("ML", "RECO_PROG_PROGS_META_LATEST", "program_id"),
    TableIdentity("ML", "RECO_PROG_PROGS_POPULAR_LATEST", "program_id"),
    TableIdentity("ML", "RECO_CHANNEL_TAGS_LATEST", "channel_id"),
    TableIdentity("ML", "RECO_USER_PERSON_LATEST", "user_id"),
]

common_backend_tables = [
    TableIdentity("BACKEND", "ACCOUNTING_ENTRY", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_EVENT", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_INVOICE", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_PAYMENT", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_PAYMENT_ATTEMPT", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_PAYMENT_CHARGE", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_PAYPAL_ATTEMPT", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_PAYPAL_CHARGE", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_PAYPAL_ENTRY", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_PAYPAL_EVENT", "id"),
    TableIdentity("BACKEND", "ACCOUNTING_PAYPAL_INVOICE", "id"),
    TableIdentity("BACKEND", "ACTUAL_RECORDING", "id"),
    TableIdentity("BACKEND", "ADVERT_ACTION", "id"),
    TableIdentity("BACKEND", "ADVERT_PLACEMENT", "id"),
    TableIdentity("BACKEND", "ASSET_VIDEO", "id"),
    TableIdentity("BACKEND", "BOOKMARK_RECORDING", "id"),
    TableIdentity("BACKEND", "BROADCAST", "id"),
    TableIdentity("BACKEND", "CAMPAIGN_MARKETING", "id"),
    TableIdentity("BACKEND", "CHANNEL", "id"),
    TableIdentity("BACKEND", "CHANNEL_GROUP", "id"),
    TableIdentity("BACKEND", "CMP_USER_CONSENTS", "user_id"),
    TableIdentity("BACKEND", "EDITO_PROGRAM", "id"),
    TableIdentity("BACKEND", "EPISODE", "id"),
    TableIdentity("BACKEND", "ETL_MAPPING_PLURIMEDIA_GENRE_TO_CATEGORY_AND_KIND", "id"),
    TableIdentity("BACKEND", "OPTINS", "id"),
    TableIdentity("BACKEND", "PAYWALL", "id"),
    TableIdentity("BACKEND", "PAYWALL_CAMPAIGN", "id"),
    TableIdentity("BACKEND", "PAYWALL_CHUNK", "id"),
    TableIdentity("BACKEND", "PAYWALL_REPORT", "task_id"),
    TableIdentity("BACKEND", "PERSON", "id"),
    TableIdentity("BACKEND", "PICTURE", "id"),
    TableIdentity("BACKEND", "PRODUCT", "id"),
    TableIdentity("BACKEND", "PRODUCT_FEATURE", "id"),
    TableIdentity("BACKEND", "PRODUCT_FEATURE_GROUP", "id"),
    TableIdentity("BACKEND", "PRODUCT_RATE_PLAN", "id"),
    TableIdentity("BACKEND", "PRODUCT_RATE_PLAN_CHARGE", "id"),
    TableIdentity("BACKEND", "PROGRAM", "id"),
    TableIdentity("BACKEND", "PROGRAM_RATING", "id"),
    TableIdentity("BACKEND", "PROGRAM_RATING_SERVICES", "id"),
    TableIdentity("BACKEND", "PROGRAM_RATING_TYPE", "id"),
    TableIdentity("BACKEND", "PROMOCODE", "id"),
    TableIdentity("BACKEND", "PROMOCODE_CAMPAIGN", "id"),
    TableIdentity("BACKEND", "PROMOCODE_PARTNER", "id"),
    TableIdentity("BACKEND", "REF_CAMPAIGN_ACTION", "id"),
    TableIdentity("BACKEND", "REF_PERSON_FUNCTION", "id"),
    TableIdentity("BACKEND", "REF_PERSON_FUNCTION_GROUP", "id"),
    TableIdentity("BACKEND", "REF_PROGRAM_CATEGORY", "id"),
    TableIdentity("BACKEND", "REF_PROGRAM_FORMAT", "id"),
    TableIdentity("BACKEND", "REF_PROGRAM_KIND", "id"),
    TableIdentity("BACKEND", "REF_REPLAY_PROVIDER", "id"),
    TableIdentity("BACKEND", "REF_TAG", "id"),
    TableIdentity("BACKEND", "REL_EPISODE_PERSON", "episode_id"),
    TableIdentity("BACKEND", "REL_EPISODE_TAG", "episode_id"),
    TableIdentity("BACKEND", "REL_PRODUCT_FEATURE", "product_id"),
    TableIdentity("BACKEND", "REL_PROGRAM_PERSON", "program_id"),
    TableIdentity("BACKEND", "REL_PROMOCODE_CAMPAIGN_PRODUCT_RATE_PLAN", "campaign_id"),
    TableIdentity("BACKEND", "REL_PROMOCODE_USER_SUBSCRIPTION", "user_subscription_id"),
    TableIdentity("BACKEND", "REL_SUBSCRIPTION_PAYMENT", "payment_id"),
    TableIdentity("BACKEND", "REL_TVBUNDLE_CHANNEL", "tvbundle_id"),
    TableIdentity("BACKEND", "REL_USER_BOOKMARK_METRICS", "user_id"),
    TableIdentity("BACKEND", "REL_WINBACK_USER_SUBSCRIPTION", "id"),
    TableIdentity("BACKEND", "REPLAY", "id"),
    TableIdentity("BACKEND", "SEASON", "id"),
    TableIdentity("BACKEND", "SUBSCRIBERS", "user_id"),
    TableIdentity("BACKEND", "TAXATION", "id"),
    TableIdentity("BACKEND", "TVBUNDLE", "id"),
    TableIdentity("BACKEND", "USER_APPLE_RECEIPT", "id"),
    TableIdentity("BACKEND", "USER_APPLE_RECEIPT_PURCHASE", "transaction_id"),
    TableIdentity("BACKEND", "USER_DEVICE", "id"),
    TableIdentity("BACKEND", "USER_DOWNLOAD", "id"),
    TableIdentity("BACKEND", "USER_FOLLOW_PERSON", "user_id"),
    TableIdentity("BACKEND", "USER_LIKE", "user_id"),
    TableIdentity("BACKEND", "USER_OPTIN", "user_id"),
    TableIdentity("BACKEND", "USER_PROFILE", "id"),
    TableIdentity("BACKEND", "USER_RAW", "id"),
    TableIdentity("BACKEND", "USER_SOURCE", "user_id"),
    TableIdentity("BACKEND", "USER_SUBSCRIPTION", "id"),
    TableIdentity("BACKEND", "VOD", "id")
]
